version: '3.9'

services:
  database:
    image: postgres
    container_name: database_teste_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=84150440
      - POSTGRES_DB=teste
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
    driver: local